added validator messages to seed data
AdExNetwork/adex-validator-stack-rust pull request #371
Opened 2021-01-18 17:15 UTC by simzzz

2021-01-19 08:53 UTC, elpiel requested changes

2021-01-19 08:53 UTC, elpiel commented on sentry/migrations/20190806011140_initial-tables/seed/up.sql
>      '{"targeting_rules": [], "minPerImpression":"1","maxPerImpression":"10","created":1564383600000,"pricingBounds":{"CLICK":{"min":"0","max":"0"}},"withdrawPeriodStart":4073414400000,"validators":[{
Can you also update the `channel_deposit` it's currently 1000, but that's not right for DAI

2021-01-19 08:53 UTC, elpiel commented on sentry/migrations/20190806011140_initial-tables/seed/up.sql
> +    '{"type":"NewState","balances":{"0x1E810Bc144EBA2C4acd9f0FFa1b07525A9c1F704":"42480633000000000000","0x5d62321228bC75936dd29f9c129f8DbDfcB93264":"9990060000000000000","0x9b88bcc2824FC929DbF646A9A
This doesn't seem to be right. This `NewState` has way to many balances and addresses + it says it's exhausted.

2021-01-20 12:13 UTC, elpiel submitted a review, later dismissed

2021-01-20 12:33 UTC, samparsky commented
We need to create a separate channel with channelId if we want to seed `validator_messages`. The channelId used here is used in tests and will result in tests failing because of the seeded validator messages

2022-06-01 12:12 UTC, closed without merging