Channel v5 table
AdExNetwork/adex-validator-stack-rust pull request #432
Opened 2021-09-17 12:29 UTC by elpiel

2021-09-20 19:34 UTC, simzzz requested changes

2021-09-20 19:34 UTC, simzzz commented on sentry/src/db/campaign.rs
> +/// SELECT campaign.id, creator, budget, validators, title, pricing_bounds, event_submission, ad_units, targeting_rules, campaign.created, active_from, active_to,
should be `campaigns.id` and `campaigns.created`

2021-09-20 19:34 UTC, simzzz commented on sentry/src/db/campaign.rs
> +/// SELECT campaigns.id, creator, budget, validators, title, pricing_bounds, event_submission, ad_units, targeting_rules, created, active_from, active_to,
should be `campaigns.created`

2021-09-20 19:34 UTC, simzzz commented on sentry/src/db/campaign.rs
> +/// UPDATE campaigns SET budget = $1, validators = $2, title = $3, pricing_bounds = $4, event_submission = $5, ad_units = $6, targeting_rules = $7 FROM campaigns INNER JOIN channels ON campaigns.chan
Should be `FROM channels` instead. The comment also uses `INNER JOIN ... ON` while the statement below does not.

2021-09-20 19:34 UTC, simzzz commented on sentry/src/db/channel.rs
> +        .prepare("SELECT leader, follower, guardian, token FROM channels WHERE id = $1 LIMIT 1")
Shouldn't `nonce` also be selected?

2021-09-21 07:04 UTC, elpiel commented on sentry/src/db/channel.rs
> +        .prepare("SELECT leader, follower, guardian, token FROM channels WHERE id = $1 LIMIT 1")
Yes, it should. Good catch!

2021-09-21 07:15 UTC, elpiel commented on sentry/src/db/campaign.rs
> +/// SELECT campaigns.id, creator, budget, validators, title, pricing_bounds, event_submission, ad_units, targeting_rules, created, active_from, active_to,
fixed

2021-09-21 07:15 UTC, elpiel commented on sentry/src/db/campaign.rs
> +/// SELECT campaign.id, creator, budget, validators, title, pricing_bounds, event_submission, ad_units, targeting_rules, campaign.created, active_from, active_to,
fixed

2021-09-21 07:17 UTC, elpiel commented on sentry/src/db/campaign.rs
> +/// UPDATE campaigns SET budget = $1, validators = $2, title = $3, pricing_bounds = $4, event_submission = $5, ad_units = $6, targeting_rules = $7 FROM campaigns INNER JOIN channels ON campaigns.chan
I've updated the full query!

2021-09-21 13:02 UTC, simzzz approved these changes

2021-09-21 14:12 UTC, merged

2021-09-21 14:12 UTC, elpiel commented
:raised_hands: :raised_hands: :raised_hands: