Analytics recorder v5
AdExNetwork/adex-validator-stack-rust pull request #449
Opened 2021-10-22 13:07 UTC by simzzz

2021-10-22 16:15 UTC, elpiel requested changes

2021-10-22 16:15 UTC, elpiel commented on primitives/src/analytics.rs
> +impl fmt::Display for OperatingSystem {
You can use `parse-display` instead. It's already added to `primitives`

2021-10-22 16:15 UTC, elpiel commented on primitives/src/sentry.rs
> +
This should be allowed only for `postgres` features.
Do the same thing as the rest of the `From<&Row>` impls - a module

2021-10-22 16:15 UTC, elpiel commented on sentry/migrations/20190806011140_initial-tables/up.sql
> +    "time" TIMESTAMP NOT NULL,
- [x] timestamp(2) with time zone

2021-10-22 16:15 UTC, elpiel commented on primitives/src/ipfs.rs
> +}
- [x] mod postgres enabled by feature postgres

2021-10-22 16:15 UTC, elpiel commented on primitives/src/ipfs.rs
> +use std::error::Error as StdError;
You won't need this renaming once you move the impls to a module.

2021-10-26 10:34 UTC, elpiel requested changes

2021-10-26 10:34 UTC, elpiel commented on sentry/src/analytics.rs
> +        let payout_amount = event_payout.values().sum::<Option<UnifiedNum>>().unwrap(); // TODO: Remove
- [x] Please move this somewhere at the beginning of the function. This will make sure that we fail fast rather than doing unnecessary work and then failing.
- [x] Include the `payout` in the `EventAnalytics` instead of sending it separately

2021-10-26 10:34 UTC, elpiel commented on sentry/src/analytics.rs
> +    events_with_payouts: Vec<(Event, HashMap<Address, UnifiedNum>)>,
- [x] This should be a vec of `(Event, Address, UnifiedNum)`. We will not record the validator fees so we only need the payout to the address.

2021-10-26 10:34 UTC, elpiel commented on sentry/src/analytics.rs
> +                    .find(|ad_unit| ad_unit.ipfs == ipfs)
```suggestion
                campaign
                    .ad_units
                    .iter()
                    .find(|ad_unit| ad_unit.ipfs == ipfs)
                    .clone()
```

2021-10-26 10:34 UTC, elpiel commented on sentry/src/analytics.rs
> +    session: Session,
```suggestion
    campaign: &Campaign,
    session: &Session,
```

2021-10-26 10:34 UTC, elpiel commented on sentry/migrations/20190806011140_initial-tables/up.sql
> +CREATE TABLE analytics (
- [x] You must update the `down.sql`

2021-10-26 10:34 UTC, elpiel commented on sentry/src/db/analytics.rs
> +    ON CONFLICT ON CONSTRAINT channels_pkey DO UPDATE
- [x] `channel_pkey` is the wrong key

2021-10-26 10:34 UTC, elpiel commented on sentry/src/db/analytics.rs
> +    RETURNING *";
- [x] specify each field, it's usually better for the query.

2021-10-26 10:34 UTC, elpiel commented on sentry/src/db/analytics.rs
> +    let query = "INSERT INTO events
- [x] The table is not called `events`

2021-10-26 10:34 UTC, elpiel commented on sentry/src/db/analytics.rs
> +pub async fn insert_analytics(
- [x] Add documentation specifying that it will update a record when it's present and how it will do it (based on the `hour`). We should thing about these function names as they create a wrong impression that it will only insert new records.

2021-10-26 10:34 UTC, elpiel commented on sentry/src/db/analytics.rs
> +    VALUES ($1, date_trunc('hour', $2), $3, $4, $5, $6, $7, $8, $9, $10, $11, 1)
- [x] please use a prepared value for the `1` and bind it to a variable e.g. `initial_count` and put it on top of the function.

2021-10-26 10:34 UTC, elpiel commented on primitives/src/ipfs.rs
> +mod postgres {
- [x] Where is the config attribute? Please check how we've done this in other modules

2021-10-26 10:34 UTC, elpiel commented on sentry/src/db/analytics.rs
> +                &event.ad_slot,
- [x] `AdUnit` implements `To` & `FromSql`, so it shouldn't require `Json()`
- [x] `AdSlot`, however, does not so please implement it.

2021-10-26 10:40 UTC, elpiel requested changes
- [x] Test the `fn record()`
- [ ] Test the `insert_analytics` query.

2021-10-26 10:40 UTC, elpiel commented on sentry/src/db/analytics.rs
> +                &event.os_name.to_string(),
- [x] implement `ToSql` & `FromSql` as you will need it when fetching data from DB

2021-10-26 10:40 UTC, elpiel commented on sentry/src/analytics.rs
> +        let event_for_db = EventAnalytics {
- [x] Where is the `event_type` field? please add that too.

2021-10-26 10:40 UTC, elpiel commented on sentry/migrations/20190806011140_initial-tables/up.sql
> +);
- [x] usually we use all capital letters when doing the event types. See the `AsRef<str> for Event`. However, you might just use `Varchar` for the field instead and use the value from `Event.to_string()` for the event type for now.

2021-10-26 10:42 UTC, elpiel commented on primitives/src/analytics.rs
> +}
Please double check if this could be done using Serde alone with `#[serde(transparent)` for the `Whitelisted` option and custom deserialize function to validate the whitelisted value when deserializing.

- [x] Write a test verifying that it can be done using only serde (e.g. use serde_json to serialize and validate the expected json)
- [x] test both Deserialize & Serialize

2021-10-26 18:43 UTC, simzzz commented on sentry/src/db/analytics.rs
> +                &event.ad_slot,
We are getting just the IPFS for the `AdSlot` so it should be fine. I will rename the field for better clarity

2021-10-28 12:52 UTC, elpiel requested changes
- [x] Test `FromSql` / `ToSql` for `OperatingSystems` - there is a bug there :wink: 
- [x] test `db::analytics::insert_analytics()`
- [x] test `analytics::record()`

2021-10-28 12:52 UTC, elpiel commented on sentry/src/db/analytics.rs
> +    RETURNING (campaign_id, time, ad_unit, ad_slot, ad_slot_type, advertiser, publisher, hostname, country, os, event_type, payout_amount, payout_count)", initial_count);
- [x] please use the prepared statement bellow for when using `initial_count`

2021-10-28 12:52 UTC, elpiel commented on sentry/migrations/20190806011140_initial-tables/down.sql
> +DROP TABLE event_aggregates, validator_messages, channels, analytics;
Please make sure that `down.sql` works properly.
I've forgotten to add some tables for dropping (like `campaigns`) but also this would probably fail when there are records in the tables because of `ON DELETE RESTRICT`

- [x] First, drop all foreign keys
- [x] Please add all tables to `DROP TABLE`, like `campaigns`
- [x] Make sure that `down.sql` works when records are present.

2021-11-11 12:25 UTC, elpiel approved these changes

2021-11-11 12:34 UTC, merged