Analytics routes
AdExNetwork/adex-validator-stack-rust pull request #461
Opened 2021-11-29 14:40 UTC by simzzz

2021-12-02 11:21 UTC, elpiel requested changes

2021-12-02 11:21 UTC, elpiel commented on docs/config/ganache.toml
> +admins = ['0xce07CbB7e054514D590a0262C93070D838bFBA2e']
You can use the real ganache ID.
Find it here:
https://github.com/AmbireTech/adex-validator-stack-rust/blob/bfdc4f75df7783350bc67ce5418ad0a79c747c93/primitives/src/test_util.rs?_pjax=%23js-repo-pjax-container%3Afirst-of-type%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%3Afirst-of-type%2C%20%5Bdata-pjax-container%5D%3Afirst-of-type#L8

2021-12-02 11:21 UTC, elpiel commented on primitives/src/analytics.rs
> +    pub fn get_period_in_hours(&self) -> i64 {
keep it simple: `to_hours`, also consider using u32, u64

2021-12-02 11:21 UTC, elpiel commented on primitives/src/sentry.rs
> +}
```
.then(aggr => ({
			limit: appliedLimit,
			limitReached: appliedLimit === aggr.length,
			aggr
		}))
```

While the aggr is:

```
const resultProjection = {
		value: '$value',
		time: {
			$toLong: {
				$dateFromParts: {
					year: { $ifNull: ['$_id.time.year', 0] },
					month: { $ifNull: ['$_id.time.month', 1] },
					day: { $ifNull: ['$_id.time.day', 1] },
					hour: { $ifNull: ['$_id.time.hour', 0] },
					timezone: timezone || 'UTC'
				}
			}
		},
		segment: '$_id.segment',
		_id: 0
	}
```
You can read what each part does, like `toLong` in Mongo docs to see what we should return at the end:
https://docs.mongodb.com/manual/reference/operator/aggregation/toLong/

It will be even better if you double check what the JS implementation returns as a json at the end.

2021-12-02 11:21 UTC, elpiel commented on sentry/src/db/analytics.rs
> +    auth_uid: ValidatorId,
You can use an enum for this. `AuthenticateAs::Advertiser(Address)`, ``AuthenticateAs::Publisher(Address)``

2021-12-02 11:21 UTC, elpiel commented on sentry/src/db/analytics.rs
> +        ),
Use a vec for each of the clauses. This complicated query needs more than just strings.
You can still build the 2 vec based on the segment if you want to keep the ordering of the clauses (for groups in particular):
```
let mut select = vec!["time".to_string(), query.metric.to_string()];
let mut order_by = vec!["time".to_string()];

match Some(segment_by) = segment_by {
select.push(...);
order_by.push(...);
}
```

When building select SQL:

select.join(',')
order_bu.join(',')

2021-12-02 11:21 UTC, elpiel commented on sentry/src/db/analytics.rs
> +        format!("event_type = ${}", query.event_type),
$1 $2 $3 is for prepared statements.
You've removed `params.len()` so the number for the parameter in the SQL query will be wrong.

2021-12-02 11:23 UTC, elpiel commented on primitives/src/analytics.rs
> +    pub end: Option<DateTime<Utc>>,
We should probably deserialize directly into DateHour.

Also, the `Joi` package usually supports both date (String) & milliseconds (number) but we have to double check if we are going to just leave it to milliseconds.
We use milliseconds almost everywhere in the JSON representaiton.

for more details check:
https://joi.dev/api/?v=17.5.0#date

2021-12-02 11:23 UTC, elpiel commented on primitives/src/analytics.rs
> +    pub campaign_id: Option<String>,
this is not a string.

2021-12-02 11:23 UTC, elpiel commented on primitives/src/analytics.rs
> +    pub ad_slot: Option<String>,
`IPFS`

2021-12-02 11:24 UTC, elpiel commented on primitives/src/analytics.rs
> +    pub publisher: Option<String>,
`Address`

2021-12-02 11:25 UTC, elpiel requested changes

2021-12-02 11:25 UTC, elpiel commented on primitives/src/analytics.rs
> +    pub os_name: Option<String>,
`OperatingSystem`

2021-12-02 12:32 UTC, simzzz commented on primitives/src/analytics.rs
> +    pub fn get_period_in_hours(&self) -> i64 {
it's always positive and it's used in `Duration::hours()` which takes i64

2021-12-31 16:42 UTC, elpiel commented
TODOs:
- [ ] Check (aka test) impls for Ord, PartialOrd, PartialEq for DateHour

2022-01-17 19:17 UTC, simzzz commented
LGTM, I think the changes reduce the complexity of the logic we had in some places.

2022-01-18 12:11 UTC, elpiel approved these changes

2022-01-18 12:11 UTC, merged

2022-01-18 12:12 UTC, elpiel commented
> TODOs:
> 
>     * [x]  Check (aka test) impls for Ord, PartialOrd, PartialEq for DateHour
> 
>     * [x]  More tests for `query::Time`
> 
>     * [ ]  Deserialize DateHour from either timestamp or ISO format
> 
>     * [ ]  Caching analytics (if needed)

I'm moving the last 2 TODOs to the #382 issue, these can be implemented on later stage.