Issue #471 Route `POST /units-for-slot`
AdExNetwork/adex-validator-stack-rust pull request #480
Opened 2022-03-18 10:27 UTC by elpiel

Part of #471 

The initial move of the `GET /units-for-slot` route from the Supermarket to sentry `POST /units-for-slot`

2022-04-01 16:16 UTC, simzzz requested changes

2022-04-01 16:16 UTC, simzzz commented on sentry/src/main.rs
> +    // todo: Make platform_url configurable! Load from config or pass with env. variable
We have those values in the config. Can't we just load them from config now?

2022-04-01 16:16 UTC, simzzz commented on primitives/src/config.rs
> +// TODO: use `milliseconds_to_std_duration` for all u32 values with "In milliseconds" in docs.
Is the `rename_all` attribute removed on purpose?

2022-04-01 16:16 UTC, simzzz commented on sentry/src/db/campaign.rs
> +    where_clauses.push("active_to >= $4".into());
`active_to` is added twice

2022-04-01 16:16 UTC, simzzz commented on sentry/src/routes/units_for_slot.rs
> +pub(crate) static CLOUDFLARE_IPCOUNTY_HEADER: Lazy<HeaderName> =
The variable is `IPCOUNTY`, should be `IPCOUNTRY`

2022-04-04 06:26 UTC, elpiel commented on primitives/src/config.rs
> +// TODO: use `milliseconds_to_std_duration` for all u32 values with "In milliseconds" in docs.
yep, it is. I've decided to drop it since we are no longer bound to the flat structure of the Config

2022-04-04 06:52 UTC, elpiel commented on sentry/src/main.rs
> +    // todo: Make platform_url configurable! Load from config or pass with env. variable
it's fixed now.

2022-04-04 07:08 UTC, elpiel commented on sentry/src/db/campaign.rs
> +    where_clauses.push("active_to >= $4".into());
fixed.

2022-04-04 08:59 UTC, elpiel commented on sentry/src/routes/units_for_slot.rs
> +pub(crate) static CLOUDFLARE_IPCOUNTY_HEADER: Lazy<HeaderName> =
fixed

2022-04-05 11:33 UTC, elpiel commented on primitives/src/campaign.rs
>  }
This is redundant, so it should be remove soon

2022-04-05 11:33 UTC, elpiel commented on primitives/src/campaign.rs
> +    pub struct PricingBounds(HashMap<EventType, Pricing>);
Pricing bounds is now using the EventType

2022-04-11 14:02 UTC, simzzz requested changes
One more thing I forgot to comment during my previous review. Other than that LGTM.

2022-04-11 14:02 UTC, simzzz commented on test_harness/src/lib.rs
> +            .expect("Should make PlatformApi");
```suggestion
       let platform_api = PlatformApi::new(
          config.platform.url.clone(),
          config.platform.keep_alive_interval,
      )
      .expect("Failed to build PlatformApi");
```

We can use the values from config here as well.

2022-04-12 10:19 UTC, merged