Bugfix UnifiedNum math operations
AdExNetwork/adex-validator-stack-rust pull request #492
Opened 2022-05-16 14:57 UTC by elpiel

2022-05-19 11:31 UTC, simzzz requested changes

2022-05-19 11:31 UTC, simzzz commented on primitives/src/unified_num.rs
> +    /// This method returns the inner [`u64`] representation of the [`UnifiedNum`].
The comment is wrong

2022-05-19 11:31 UTC, simzzz commented on sentry/src/routes/units_for_slot_test.rs
> +use crate::{platform::PlatformApi, test_util::setup_dummy_app};
I think this file should belong to another PR

2022-05-20 12:30 UTC, elpiel commented on primitives/src/unified_num.rs
> +    /// This method returns the inner [`u64`] representation of the [`UnifiedNum`].
Good catch

2022-05-20 12:30 UTC, elpiel commented on sentry/src/routes/units_for_slot_test.rs
> +use crate::{platform::PlatformApi, test_util::setup_dummy_app};
Hmm yeah, I don't know how that got here...

2022-05-23 09:56 UTC, simzzz approved these changes

2022-05-24 08:43 UTC, merged