added get_leaf route + tests
AdExNetwork/adex-validator-stack-rust pull request #544
Opened 2022-08-19 12:16 UTC by simzzz

2022-08-19 12:23 UTC, simzzz commented
TODO:

- [ ] Fix te failing test + maybe find a better testing approach
- [ ] Documentation for route
- [ ] Code examples for GetLeafResponse

2022-08-19 17:47 UTC, elpiel requested changes

2022-08-19 17:47 UTC, elpiel commented on sentry/src/routes/channel.rs
> +    .map_err(|err| ResponseError::BadRequest(err.to_string()))?;
You can remove this `map_err` because ResponseError has an impl From for any Error and will automatically create BadRequest with String error instide.

2022-08-19 17:47 UTC, elpiel commented on sentry/src/routes/channel.rs
> +    let signable_state_root = get_signable_state_root(&*channel.id(), &merkle_tree.root());
Use `as_bytes` instead of `&*channel.id(`

2022-08-19 17:47 UTC, elpiel commented on sentry/src/routes/channel.rs
> +        MerkleTree::new(&[element]).map_err(|err| ResponseError::BadRequest(err.to_string()))?;
same goes for this error mapping

2022-08-19 17:47 UTC, elpiel commented on sentry/src/routes/channel.rs
> +                &*ADVERTISER,
you probably don\t need `&*`, just `&` is enough

2022-08-19 17:49 UTC, elpiel commented
Also take into account what we've discussed on slack how to set the earner/spender sides.
`enum LeafFor { Spender, Earner}` and add it to the respective route as an `Extension`

2022-08-30 10:17 UTC, elpiel requested changes
Look pretty good. A few polishing touches on Errors remain and a few tests regarding:

- no ApproveState - 404
- no NewState (but has approvestate) - 400
- no spender/earner - you could use the same address and call the function twice

2022-08-30 10:17 UTC, elpiel commented on sentry/src/routes.rs
> +//! #### GET `/v5/channel/:id/get-leaf/spender` and GET `/v5/channel/:id/get-leaf/earner`
This will break the link on top of the docs. I would say to leave it "GET `/v5/channel/:id/get-leaf`" and add the sub-routes in a list below the header `####`, e.g.

```
- GET `/v5/channel/:id/get-leaf/spender/0x....` - for Channel spender leaf
- GET `/v5/channel/:id/get-leaf/earner/0x....` - for Channel earner leaf
```

2022-08-30 10:17 UTC, elpiel commented on sentry/src/routes.rs
> +//! `/get-leaf/earner/0x....`
we can add these examples with actual addresses below in the `Examples` section as e.g. `URI` above `Response`.

2022-08-30 10:17 UTC, elpiel commented on sentry/src/routes/channel.rs
> +/// GET `/v5/channel/0xXXX.../get-leaf/earner` request
I would say we should do the same as in the route documentation - "GET `/v5/channel/0xXXX.../get-leaf`" and list the 2 routes for earner & spender below in a list.

2022-08-30 10:17 UTC, elpiel commented on sentry/src/routes/channel.rs
> +            ))
Could you please use 404 in this case. A channel can be new and might not have an ApproveState yet. This shouldn't be a `BadRequest` (400) error.

2022-08-30 10:17 UTC, elpiel commented on sentry/src/routes/channel.rs
> +        .ok_or_else(|| ResponseError::BadRequest("No NewState message for spender".to_string()))?;
This should remain the same. If there is an ApproveState, then there must be a NewState that was approved, so 400 is good.

2022-08-30 10:17 UTC, elpiel commented on sentry/src/routes/channel.rs
> +                ResponseError::BadRequest("No balance entry for spender!".to_string())
We should use 404 - Not Found.

2022-08-30 10:17 UTC, elpiel commented on sentry/src/routes/channel.rs
> +                ResponseError::BadRequest("No balance entry for spender!".to_string())
use 404 here as well

2022-08-31 08:37 UTC, merged